# Generated by Django 6.0.5 on 2026-06-02 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_postcomment_delete_post'),
        ('User', '0002_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='user',
            field=models.ForeignKey(db_column='user_username', on_delete=django.db.models.deletion.CASCADE, related_name='post_comments', to='User.user', to_field='username', verbose_name='댓글 작성자'),
        ),
    ]
