# Generated by Django 6.0.5 on 2026-06-01 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='계획 이름')),
                ('content', models.TextField(blank=True, null=True, verbose_name='계획 내용')),
                ('deadline', models.DateTimeField(verbose_name='데드라인')),
                ('status', models.CharField(choices=[('PENDING', '대기'), ('SUCCESS', '성공'), ('FAIL', '실패')], default='PENDING', max_length=10, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'db_table': 'plans',
            },
        ),
    ]
