# Generated by Django 6.0.5 on 2026-06-02 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='ai_duration_hours',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='AI 예측 소요 시간(시간)'),
        ),
        migrations.AddField(
            model_name='plan',
            name='assigned_date',
            field=models.DateField(blank=True, null=True, verbose_name='계획 배치 날짜'),
        ),
        migrations.AddField(
            model_name='plan',
            name='category',
            field=models.CharField(default='기타', max_length=100, verbose_name='큰 분류 (카테고리)'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='사용자 설정 데드라인'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PlanHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='큰 분류 (카테고리)')),
                ('title', models.CharField(max_length=255, verbose_name='계획 이름')),
                ('completed_at', models.DateField(verbose_name='실제 수행일')),
                ('result', models.CharField(choices=[('SUCCESS', '성공'), ('FAIL', '실패')], max_length=10, verbose_name='성공 여부')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_histories', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'db_table': 'plan_histories',
                'ordering': ['-completed_at'],
            },
        ),
    ]
