# Generated by Django 6.0.5 on 2026-06-02 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plan', '0003_alter_plan_user'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planhistory',
            name='user',
            field=models.ForeignKey(db_column='user_username', on_delete=django.db.models.deletion.CASCADE, related_name='plan_histories', to='User.user', to_field='username', verbose_name='작성자'),
        ),
    ]
