# Generated by Django 6.0.5 on 2026-06-02 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plan', '0004_alter_planhistory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_shared',
            field=models.BooleanField(default=False, verbose_name='게시판 공유 여부'),
        ),
        migrations.AddField(
            model_name='planhistory',
            name='is_shared',
            field=models.BooleanField(default=False, verbose_name='게시판 공유 여부'),
        ),
    ]
