# Generated by Django 6.0.5 on 2026-06-01 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='아이디')),
                ('password', models.CharField(max_length=128, verbose_name='비밀번호')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='가입일')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
