# Generated by Django 6.0.5 on 2026-06-02 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='친구 맺은 날짜')),
                ('from_user', models.ForeignKey(db_column='from_user_username', on_delete=django.db.models.deletion.CASCADE, related_name='from_users', to='User.user', to_field='username', verbose_name='나')),
                ('to_user', models.ForeignKey(db_column='to_user_username', on_delete=django.db.models.deletion.CASCADE, related_name='to_users', to='User.user', to_field='username', verbose_name='친구')),
            ],
            options={
                'db_table': 'friends',
                'constraints': [models.UniqueConstraint(fields=('from_user', 'to_user'), name='unique_friendship')],
            },
        ),
    ]
